[libraries]

lib.files = [
"UE_8\\tilt_board_debug_tb.vhd",
"UE_8\\tilt_board_debug_ea.vhd",
"UE_8\\tilt_board_combined_debug_ea.vhd",
"UE_8\\delta_adc_debug_ea.vhd",
"UE_7\\tilt_combined_board_ea.vhd",
"UE_7\\moving_average_filter_tb.vhd",
"UE_7\\moving_average_filter_ea.vhd",
"UE_6\\tilt_tb.vhd",
"UE_6\\tilt_package.vhd",
"UE_6\\tilt_ea.vhd",
"UE_6\\tilt_board_tb.vhd",
"UE_6\\tilt_board_ea.vhd",
"UE_6\\hold_value_on_strobe_tb.vhd",
"UE_6\\hold_value_on_strobe_ea.vhd",
"UE_5\\servo_package.vhd",
"UE_5\\servo_controller_tb.vhd",
"UE_5\\servo_controller_ea.vhd",
"UE_5\\servo_controller_board_ea.vhd",
"UE_4_5\\sync_chain_tb.vhd",
"UE_4_5\\sync_chain_ea.vhd",
"UE_4_5\\LED_Blink.vhd",
"UE_4\\strobe_generator_tb.vhd",
"UE_4\\strobe_generator_e.vhd",
"UE_4\\strobe_generator_a.vhd",
"UE_4\\delta_adc_tb.vhd",
"UE_4\\delta_adc_e.vhd",
"UE_4\\delta_adc_a.vhd",
"UE_3\\pwm_tb.vhd",
"UE_3\\pwm_e.vhd",
"UE_3\\pwm_a.vhd",
"UE_2\\LED_Blinking_Tb.vhd",
"UE_2\\FSM_e.vhd",
"UE_2\\FSM_a.vhd",
"UE_2\\counter_e.vhd",
"UE_2\\counter_a.vhd",
"UE_1\\and_or_tb.vhd",
"UE_1\\and_or_e.vhd",
"UE_1\\and_or_a.vhd",
"UE_1\\adder_tb_3bit.vhd",
"UE_1\\adder_tb_2bit.vhd",
"UE_1\\adder_tb.vhd",
"UE_1\\adder_e.vhd",
"UE_1\\adder_a.vhd",
"UE_8\\debounce\\debounce_to_strobe_tb.vhd",
"UE_8\\debounce\\debounce_to_strobe_ea.vhd",
"UE_8\\debounce\\debounce_tb.vhd",
"UE_8\\debounce\\debounce_ea.vhd",
"UE_8\\button_control\\increment_control_tb.vhd",
"UE_8\\button_control\\increment_control_ea.vhd",
"UE_8\\button_control\\button_control_tb.vhd",
"UE_8\\button_control\\button_control_ea.vhd",
"UE_7\\deprecated\\unsigned_shift_register_tb.vhd",
"UE_7\\deprecated\\unsigned_shift_register_ea.vhd",
"UE_7\\deprecated\\moving_average_filter_ea.vhd",
"UE_6\\7_seg_display\\bin2bcd_ea.vhd",
"UE_6\\7_seg_display\\bcd_to_7seg_ea.vhd",
]
